### ISSUE TITLE
[feature] video support 

### ISSUE THREAD

**Issue by seagullmania** [EthanC/Bluebird#1]
will video support be added?

**Comment by EthanC** [comment]
It's not possible, unfortunately.

Apps/Bots/Webhooks can't use an embed's video property; only URL auto-embeds can use that feature.

> For the embed object, you can set every field except `type` (it will be `rich` regardless of if you try to set it), `provider`, **`video`**, and any `height`, `width`, or `proxy_url` values for images.

https://discord.com/developers/docs/resources/channel#create-message

**Comment by EthanC** [comment]
This is now possible via Components v2 and I've updated the app to support it.
