### ISSUE TITLE
The free Twitter API is simply not enough, is there anything that can replace it

### ISSUE THREAD

**Issue by szsyzx** [EthanC/Bluebird#2]
The free Twitter API is simply not enough, is there anything that can replace it

**Comment by EthanC** [comment]
If there were a better option, I would use it.

You can voice your support for my API requests at https://github.com/FixTweet/FxTwitter/issues/684 and https://github.com/dylanpdx/BetterTwitFix/issues/196. If I could utilize either one, the experience would likely be much improved.

**Comment by EthanC** [comment]
I've just replaced the internal Twitter API with the API provided by https://github.com/dylanpdx/BetterTwitFix.

Give it a try and let me know what you think.
